name: Redis Keep-Alive

on:
  schedule:
    # 每4小时执行一次
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. 固定到稳定的 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install redis

      # 2. 移除已弃用的 ssl_cert_reqs 参数
      - name: Run Python Keep-Alive Script
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          python -c "
          import redis, os, datetime
          r = redis.from_url(os.getenv('REDIS_URL'), decode_responses=True)
          r.set('github_actions:keep_alive_timestamp', datetime.datetime.now().isoformat())
          print('Redis keep-alive ping sent successfully.')
          "
